branch-defaults:
  local:
    environment: jackson-rs-glue-prod
  master:
    environment: jackson-rs-glue-prod
  test:
    environment: jackson-rs-glue-prod
deploy:
  artifact: release-candidate.zip
global:
  application_name: jackson-rs-glue
  default_ec2_keyname: BuildcaveKeyPair
  default_platform: 64bit Amazon Linux 2016.03 v2.1.0 running Docker 1.11.2
  default_region: us-east-1
  profile: null
  sc: git
